spring:
  data:
    auditing:
      enabled: true

  application:
    name: seek-with-sight
    security:
      jwt:
        secret-key: ${JWT_SECRET}
        # 30 min in ms
        access-token-expiration: 1800000
        # 7 days in ms
        refresh-token-expiration: 604800000
        refresh-cookie-path: /api/auth
        refresh-cookie-same-site: Strict

  datasource:
    url: ${SWS_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  error:
    include-stacktrace: never
    include-message: never