spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  flyway:
    enabled: false

server:
  port: 8443
  ssl:
    enabled: true
    key-store: "classpath:keystore.p12"
    key-store-password: "password"
    key-store-type: PKCS12
    key-alias: "keystoreDev"

logging:
  level:
    root: INFO
    com.seek_with_sight: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

app:
  base-url: "https://localhost:8443"

  storage:
    root-dir: uploads
    public-base-url: ${app.base-url}/${app.storage.root-dir}