name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

      
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: maven

        
    - name: Build with Maven
      run: mvn -B package --file pom.xml


    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: maven-target
        path: target/

  sonarqube:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven-target
          path: target/


      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=gabrielzdenekes_seek-with-sight-server
            -Dsonar.organization=seek-with-sight-server
            -Dsonar.java.binaries=target/classes
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
